name: Clash-for-Windows Update Check

on:
  schedule: 
    - cron: '0 2/2 * * *'

  workflow_dispatch:


jobs:
  update:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install requirements
      run: pip install requests python-dotenv PyGithub

    - name: Run Python Script
      run: 
        python main.py
env:
  TG_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TG_CHAT_ID: ${{ secrets.CHANNEL_ID }}
  token: ${{ secrets.PAT }}
